### ISSUE TITLE
Any save function?

### ISSUE THREAD

**Issue by hebroin** [Rohul1997/TFFCC-Save-Editor#1]
Nice work you do there. Is there any save function coming or is it only informational?

Thx

**Comment by Madridi7** [comment]
That's the goal hebroin. The project is on halt at the moment though.

**Comment by Rohul1997** [comment]
oops I forgot to reply here 👀 
Ye this is still incomplete and unreleased, also on hold like Madridi said.

**Comment by hebroin** [comment]
Too bad! :)
Thx for the info
