### ISSUE TITLE
Can't load save

### ISSUE THREAD

**Issue by hebroin** [Rohul1997/TFFCC-Save-Editor#2]
Hey, 
Wonderful news on the save feature. I tried the new version, but I can't get my save to load.
It was working with the previous version but now I get the following errors :

![image](https://user-images.githubusercontent.com/11916335/37691166-4d71dbdc-2c86-11e8-8d2a-523a3f7f8dcf.png)
![image](https://user-images.githubusercontent.com/11916335/37691203-8e7182ea-2c86-11e8-9b10-74372af86547.png)

Here's the saves I am trying to load.
[saves.zip](https://github.com/Rohul1997/TFFCC-Save-Editor/files/1831783/saves.zip)

Again, thanks for your work. I know .NET, but I know nothing about save editing! :-(

**Comment by Rohul1997** [comment]
This program is still in alpha stage and not ready for use. It can potentially corrupt your save and I advise you to just wait for me to release it publicly.
